"""
core/test_generator.py
----------------------
Deterministic, rule-based regression-test generator for BugFix Agent.

This module is NOT an LLM or an AI model.  It inspects the submitted code
and the error type to produce a minimal pytest test that either:
  - Reproduces the detected bug (confirms the bug exists before the fix), or
  - Verifies the expected corrected behaviour (regression guard after the fix).

The generated test is returned as a plain Python string — it is never
executed here.  Saving and running it is the caller's responsibility.

Rules implemented
-----------------
1. ZeroDivisionError — empty-list average pattern
       Detects functions that divide by len(sequence) and generates a
       test asserting the function returns 0 for an empty input.

2. ZeroDivisionError — literal divisor pattern
       Detects a top-level ``x / 0`` or ``x // 0`` expression and generates
       a test confirming the expression raises ZeroDivisionError.

3. NameError
       Generates a test that calls the code as a module-level snippet and
       asserts a NameError is raised (documents the bug before any fix).

All other errors return success=False with an explanation.

Public interface
----------------
    generate_regression_test(code: str, error_message: str) -> dict
"""

import ast
import re
import textwrap


# ── Public interface ──────────────────────────────────────────────────────────

def generate_regression_test(code: str, error_message: str) -> dict:
    """
    Generate a minimal pytest regression test for the reported error.

    Parameters
    ----------
    code : str
        The Python source code that produced the error.
    error_message : str
        The exception type and message, e.g.
        ``"ZeroDivisionError: division by zero"``.

    Returns
    -------
    dict with keys:
        success    : bool  – True when a test was generated
        message    : str   – Short description of the outcome
        test_code  : str   – Generated pytest source (present when success=True)
    """
    stripped = error_message.strip()

    if stripped.startswith("ZeroDivisionError"):
        return _test_zero_division(code)

    if stripped.startswith("NameError"):
        return _test_name_error(code, stripped)

    exc_type = stripped.split(":")[0].strip() if ":" in stripped else stripped
    return _no_test(
        f"Regression-test generation is not yet supported for `{exc_type}`.",
        "Manual review is required to write a meaningful regression test "
        "for this error type.",
    )


# ── Rule 1 & 2: ZeroDivisionError ────────────────────────────────────────────

def _test_zero_division(code: str) -> dict:
    """
    Two sub-patterns are recognised:

    A) Empty-list average — a function whose body divides by ``len(seq)``
       where ``seq`` is a parameter.  The generated test calls the function
       with an empty list and asserts the result is 0.

    B) Literal-zero divisor — top-level ``/ 0`` or ``// 0`` expression.
       The generated test asserts that executing the expression raises
       ZeroDivisionError (documents the pre-fix behaviour).
    """
    # ── Sub-pattern A: average-over-empty-list ────────────────────────────────
    avg_func = _detect_average_function(code)
    if avg_func:
        func_name, param_name = avg_func
        test_code = textwrap.dedent(f"""\
            # Regression test generated by BugFix Agent
            # Verifies that {func_name}() handles an empty list safely.
            import pytest


            def test_{func_name}_empty_{param_name}():
                \"\"\"
                An empty {param_name} should return 0, not raise ZeroDivisionError.
                \"\"\"
                from calculator import {func_name}
                result = {func_name}([])
                assert result == 0, (
                    f"Expected 0 for empty input, got {{result}}"
                )
        """)
        return {
            "success": True,
            "message": (
                f"Generated a regression test for `{func_name}()` "
                "with an empty-list input."
            ),
            "test_code": test_code,
        }

    # ── Sub-pattern B: literal zero divisor in a simple expression ────────────
    if re.search(r'(/{1,2})\s*\b0\b(?!\.\d)', code):
        test_code = textwrap.dedent("""\
            # Regression test generated by BugFix Agent
            # Documents that the original code raises ZeroDivisionError.
            import pytest


            def test_division_by_zero_raises():
                \"\"\"
                The original expression divides by the literal 0.
                This test documents the bug; after the fix it should be updated
                to assert the corrected behavior instead.
                \"\"\"
                with pytest.raises(ZeroDivisionError):
                    _ = 1 / 0
        """)
        return {
            "success": True,
            "message": (
                "Generated a regression test that documents "
                "the ZeroDivisionError for a literal zero divisor."
            ),
            "test_code": test_code,
        }

    # Neither pattern matched
    return _no_test(
        "ZeroDivisionError detected, but the code pattern was not "
        "recognised well enough to generate a safe regression test.",
        "Write a test that checks the specific condition that causes "
        "the divisor to become zero in your code.",
    )


def _detect_average_function(code: str):
    """
    Return ``(func_name, param_name)`` if the code contains a function whose
    body divides by ``len(<param>)`` where ``<param>`` is a parameter of that
    function.  Returns None otherwise.

    This covers the canonical buggy-average pattern:

        def calculate_average(numbers):
            return sum(numbers) / len(numbers)
    """
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return None

    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef):
            continue

        param_names = {arg.arg for arg in node.args.args}
        if not param_names:
            continue

        # Look for a BinOp of the form  <anything> / len(<param>)
        for child in ast.walk(node):
            if not isinstance(child, ast.BinOp):
                continue
            if not isinstance(child.op, (ast.Div, ast.FloorDiv)):
                continue
            right = child.right
            # right must be  len(<param>)
            if not (
                isinstance(right, ast.Call)
                and isinstance(right.func, ast.Name)
                and right.func.id == "len"
                and len(right.args) == 1
                and isinstance(right.args[0], ast.Name)
                and right.args[0].id in param_names
            ):
                continue

            param_used = right.args[0].id
            return (node.name, param_used)

    return None


# ── Rule 3: NameError ─────────────────────────────────────────────────────────

def _test_name_error(code: str, error_message: str) -> dict:
    """
    Generate a test that asserts a NameError is raised when the original
    (unfixed) code is executed — documenting the bug before any fix.
    """
    match = re.search(r"name '([^']+)' is not defined", error_message)
    if not match:
        return _no_test(
            "Could not extract the missing variable name from the NameError.",
            "Write a test that verifies the variable is properly defined "
            "before it is used.",
        )

    missing_name = match.group(1)

    # Indent the code block to sit inside the with-raises body.
    # with pytest.raises is at 4 spaces; its body needs 8 spaces.
    indented = textwrap.indent(code.strip(), "        ")

    lines = [
        "# Regression test generated by BugFix Agent",
        f"# Documents that the original code raises NameError for '{missing_name}'.",
        "import pytest",
        "",
        "",
        f"def test_name_error_{missing_name}_is_undefined():",
        '    """',
        f"    The name '{missing_name}' is used before it is assigned.",
        "    This test documents the bug; update it after the fix to assert",
        "    the correct behavior instead.",
        '    """',
        "    with pytest.raises(NameError):",
        indented,
        "",
    ]
    test_code = "\n".join(lines)

    return {
        "success": True,
        "message": (
            f"Generated a regression test documenting that "
            f"`{missing_name}` raises NameError before the fix."
        ),
        "test_code": test_code,
    }


# ── Internal helper ───────────────────────────────────────────────────────────

def _no_test(message: str, explanation: str) -> dict:
    """Return a uniform failure response with no test_code field."""
    return {
        "success": False,
        "message": message,
        "explanation": explanation,
    }
